# Generated by Django 2.2 on 2023-03-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230308_1236'),
        ('cart', '0002_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='items',
        ),
    ]
